baseurl = "https://how-to-firebase.github.io/tutorials/"
languageCode = "en-us"
title = "How To Firebase: Tutorials"
theme = "hugo-material-docs"
# theme = "hugo-now-ui"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""
publishDir = "docs"

[params]
	# General information
	author = "Chris Esplin"
	description = "A series of Firebase tutorials"
	copyright = "Released under the MIT license"
	title = "How To Firebase: Tutorials"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/how-to-firebase/tutorials"

	version = "1.0.0"
	logo = "images/identity/bolt.png"
	favicon = "images/identity/bolt.png"

	permalink = "#"

	# Custom assets
	custom_css = ["styles/style.css"]
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "blue-grey"
    	accent  = "amber"

	[params.font]
		text = "Montserrat"
		code = "Ubuntu Mono"


[social]
	twitter = "ChrisEsplin"
	github  = "deltaepsilon"
	email   = "chris@chrisesplin.com"

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true

[[menu.main]]
	name   = "Introduction"
	url    = "/"
	weight = 10

[[menu.main]]
	name   = "Overview"
	url    = "overview/"
	weight = 50

[[menu.main]]
	name   = "Demo Install"
	url    = "overview/demo/"
	weight = 75

[[menu.main]]
	name   = "Firebase Dashboard"
	url    = "overview/dashboard/"
	weight = 75


[[menu.main]]
	name   = "Authentication"
	url    = "authentication/"
	weight = 100

[[menu.main]]
	name   = "Storage"
	url    = "storage/"
	weight = 200


